eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.47.7.11:8761/eureka/
      
spring:
  boot:
    admin:
      url: http://localhost:8080
  cloud:
    config:
      enabled: false

endpoints:
  health:
    sensitive: false